# Change these first
owner: AlexCK-STFC # Your GitHub organization or username, where this repository lives
repo: stfc-status-page # The name of this repository

sites:
  - name: OpenStack Horizon
    url: https://openstack.stfc.ac.uk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /stfc-status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: STFC Cloud Status
  introTitle: "Status page for the STFC Cloud"
  introMessage: This is a work-in-progress user-facing status page for the STFC Cloud
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
