# Change these first
owner: AlexCK-STFC # Your GitHub organization or username, where this repository lives
repo: stfc-status-page # The name of this repository

sites:
  - name: OpenStack Web UI (Horizon)
    url: https://openstack.stfc.ac.uk
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
  - name: OpenStack Baremetal (Ironic)
    url: https://openstack.stfc.ac.uk:6385
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
  - name: OpenStack Baremetal Introspection (Ironic-Inspector)
    url: https://openstack.stfc.ac.uk:5050/
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
  - name: OpenStack Cloudformation (Heat-CFN)
    url: https://openstack.stfc.ac.uk:8000/v1
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
  - name: OpenStack Compute (Nova)
    url: https://openstack.stfc.ac.uk:8774/v2.1
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
  - name: OpenStack Legacy Compute (Nova Legacy)
    url: https://openstack.stfc.ac.uk:8774/v2
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
  - name: OpenStack EC2 API
    url: https://openstack.stfc.ac.uk:8788/v2/
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
  - name: OpenStack Identity (Keystone)
    url: https://openstack.stfc.ac.uk:5000
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
  - name: OpenStack Identity v3 (Keystone v3)
    url: https://openstack.stfc.ac.uk:5000/v3
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
  - name: OpenStack Orchestration (Heat)
    url: https://openstack.stfc.ac.uk:8004/v1
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
  - name: OpenStack Volume (Cinder v3)
    url: https://openstack.stfc.ac.uk:8776/v3
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
  - name: OpenStack Load Balancer (Octavia)
    url: https://openstack.stfc.ac.uk:9876
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
  - name: OpenStack Shared File System (Manila)
    url: https://openstack.stfc.ac.uk:8786/v1
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
  - name: OpenStack Shared File System v2 (Manila v2)
    url: https://openstack.stfc.ac.uk:8786/v2
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
  - name: OpenStack Object Store (Swift)
    url: https://s3.echo.stfc.ac.uk/swift/v1
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
  - name: OpenStack Image (Glance)
    url: https://openstack.stfc.ac.uk:9292
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
  - name: OpenStack Network (Neutron)
    url: https://openstack.stfc.ac.uk:9696
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
  - name: OpenStack Resource Placement
    url: https://openstack.stfc.ac.uk:8778
    expectedStatusCodes:
      - 200
      - 401
      - 400
      - 300
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /stfc-status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: STFC Cloud Status
  introTitle: "Status page for the STFC Cloud"
  introMessage: This is a work-in-progress user-facing status page for the STFC Cloud
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  uptime: "*/15 * * * *"
